### ISSUE TITLE
도움말

### ISSUE THREAD

**Issue by foba1** [foba1/ITRC-KMSIS#1]

**Comment by rlawltn2714** [comment]
# 도움말

## 단축키

|단축키|기능|
|:---:|:---:|
|Ctrl + Q|분석 모드|
|Ctrl + D|건물 삭제|
|Ctrl + X|건물 삭제 초기화|
|Ctrl + C|삭제된 건물만 보기|
|Ctrl + S|건물 변화 저장|
|Ctrl + O|건물 불러오기| 
|Ctrl + R|카메라 리셋|
|W|화면 확대|
|S|화면 축소|
|A|화면 이동(좌)|
|D|화면 이동(우)|


## 기능설명

### 일조량 확인 방법

1.	일조량을 확인할 건물을 **선택**해주세요. (선택한 건물은 **초록색**으로 바뀌며, **드래그** 시 **복수 건물**이 **선택**됩니다.)
      
    ※**복수의 건물**을 **선택**할 시, 계산 양이 많아 **계산 속도**가 **느려질 수 있습니다.**

2.	**일조량 확인 버튼**을 클릭해주세요.
  
    ***최대** 일조량: 햇빛을 가장 **길게** 받은 부분의 시간
    ***평균** 일조량: 햇빛을 가장 **짧게** 받은 부분의 시간과 길게 받은 부분의 시간의 평균

### 특정 영역의 일조량 확인 방법

1.	**영역 설정 버튼**을 눌러 일조량을 확인하고자 하는 영역을 마우스로 선택해주세요.

2.	**계산 기간 설정 버튼**을 눌러 확인하고자 하는 시간을 설정해주세요.

3.	**계산 실행 버튼**을 누르면 결과를 확인하실 수 있습니다.

4.	계산 결과를 저장할 경우 **저장 버튼**을 눌러주세요. **저장기록**에 저장됩니다.

### 업로드한 건물의 일조량 확인 방법

1.	**건물배치 버튼**을 선택해주세요.

2.	업로드할 건물을 선택해주세요.

3.	건물을 놓고자 하는 위치에 **드래그**해주세요.
   
       ***사용자 모델**을 업로드할 경우 **불러오기 버튼**을 눌러주세요.

4.	위와 같은 방식으로 일조량을 확인해주세요.


 ### 세부 항목

![image](https://user-images.githubusercontent.com/93697773/142591319-ae54603b-c24a-4d4d-83c9-0c39fd783c59.png)

① 카메라 각도 조절 버튼 : **시야**를 원하는 **각도**로 **변경**, **카메라 버튼** 클릭 시 **초기 화면**으로 이동

② 카메라 확대/축소 바 : 화면의 **확대** 및 **축소**

③ 타임 슬라이더 : **노란색 바**가 우측으로 **이동**함에 따라 **시간 변경**

④ 날짜 조작 창 : 일조량을 확인할 **기간 설정**

⑤ 수치 입력 부 : 건물의 **각도**와 **크기**를 **조절**

## 시연 영상

준비중입니다.
